### ISSUE TITLE
Natural accidental twice in chor199.krn

### ISSUE THREAD

**Issue by davidrizo** [craigsapp/bach-370-chorales#16]
In line 129, the natural accidental seems to be written twice:
```4B-]	4G	8ennXXL	2cc```
Shouldn't it be?
```4B-]	4G	8enXXL	2cc```

**Comment by davidrizo** [comment]
In line 128 of chor302.krn the case is the same

**Comment by craigsapp** [comment]
Yes, that is strange and they should be `nX` rather than `nnXX`...

**Comment by craigsapp** [comment]
Fixed in commit https://github.com/craigsapp/bach-370-chorales/commit/960377a6d13997ea0d4725fa0206e88e4711ef55
