### ISSUE TITLE
`chor204.krn` Alto has additional transition C4 m. 1, b. 4

### ISSUE THREAD

**Issue by johentsch** [craigsapp/bach-370-chorales#7]
![image](https://github.com/craigsapp/bach-370-chorales/assets/42718519/a71e409e-de7e-4105-b620-19566ae756d3)

**Comment by craigsapp** [comment]
Here is the update:

<img width="715" alt="Screenshot 2023-06-21 at 12 29 01 PM" src="https://github.com/craigsapp/bach-370-chorales/assets/3487289/f5c4aef6-1fbe-4ea3-9315-94be4f38a848">

This measure is an interesting case for automatic display.  By default the second sharp was not being displayed to the the automatic accidental display system, which is currently single-instrument method, where the second sharp is not displayed.   For orchestral instruments, the accidentals are typically treated independently as in the source here.   One solution is to have an automatic visual accidental system for multiple-parts.   I did the easier method and added an `X` in the score to force the sharp to be displayed in the Grand-staff view of the score.
